version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 203065707461.dkr.ecr.us-east-1.amazonaws.com
      - APACHE_URI=203065707461.dkr.ecr.us-east-1.amazonaws.com/apache
      - NGINX_URI=203065707461.dkr.ecr.us-east-1.amazonaws.com/nginx
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $APACHE_URI:latest ./apache
      - docker build -t $NGINX_URI:latest ./nginx
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $APACHE_URI:latest
      - docker push $NGINX_URI:latest
artifacts:
  files:
    - '**/*'